development:
  adapter: postgresql
  encoding: unicode
  database: products_development
  pool: 5
  username: bon
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: products_test
  pool: 5
  username: bon
  password: